version: '3.3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "443:9000"
    command: --ssl --sslcert /fullchain.pem --sslkey /privkey.pem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
    configs:
      - fullchain.pem
      - privkey.pem
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

volumes:
  data:

networks:
  portainer_agent:
    driver: overlay
    attachable: true

configs:
  fullchain.pem:
    file: ./fullchain.pem
  privkey.pem:
    file: ./privkey.pem
