version: '3'

services:
  flask:
    image: 10.132.0.2:8000/flask
    build : flask/
    ports:
      - "5000:5000"
    depends_on:
      - celery
    networks:
      - certbot_overlay
  celery:
    image: 10.132.0.2:8000/celery
    build : celery/
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: "--appendonly yes"

volumes:
  redis-data:

networks:
  certbot_overlay:
    external: true
